Responsive cats page with filter and details
why-agency/why-test-app pull request #2
Opened 2023-11-07 11:06 UTC by TheRealChio

# 🎉 You've made a PR! 🎉

## 📋 Task

### Description of the issue/feature/bug

_Responsive website for cats where the user can filter the cats by breed and also see the details of a specific cat_

**Link to Figma**:
https://www.figma.com/file/QaAUTjri39HPaSUTEoMfWQ/Cat-Grid?type=design&node-id=0-1&mode=design
**Link to Test changes**:

## 👩‍🏭 Solution

- _Created a responsive overlay where all the cats will be displayed_ 
- _Added a sidebar for tablet and larger devices where the user can filter the cats by breed_ 
- _Clicking on a specific cat opens a window that displays the cats details_

## 🧪 Testing

_Please outline the steps to test your changes_

## ☑ Checklist

- [ ] _Have you removed all comments + console.logs?_
- [ ] _Have you tested across browsers + devices?_
- [ ] _Does your PR title fit with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?_

2023-11-07 19:47 UTC, itsjab requested changes
Looks great 🎉 

I left some feedback to prevent leaking sensitive information and make use of server components.

2023-11-07 19:47 UTC, itsjab commented on app/components/CatList.tsx
> +    url = `https://api.thecatapi.com/v1/images/search?limit=20&breed_ids=${currentQuery}&api_key=${API_KEY}`;
Using the API Key in a client component like this will expose it to outside users.

Check the network tab and you'll see the request that is made to the cat api.

General rule of thumb with Next app router is to keep request / api calls in server components.

2023-11-07 19:47 UTC, itsjab commented on app/page.tsx
>  export default function CatGrid() {
To prevent leaking the api key, you can access the cat api here in the page, which is a server component by default.

Something like this:
```ts
const response = await fetch('api.cats.com/...')
const cats = await response.json()


if (!cats || !cats.length) {
  notFound()
}

return (
  <main>...</main>
)
```

You also have access to searchParams in the page without relying on the `useSearchParams` hook, which is only available in client components.

Use the following
```ts
export default function CatGrid({ searchParams }: { searchParams: { [key: string]: string } }) {
  const response = await fetch(`api.cats.com/?${searchParams}`) // simplified example
  const cats = await response.json()
  ...
}
```

2023-11-07 19:47 UTC, itsjab commented on app/components/Sidebar.tsx
> +  useEffect(() => {
This component would also benefit from being a server component to avoid leaking any sensitive data. But looks like the cat api also works without an API key 😅

2023-11-07 19:47 UTC, itsjab commented on app/components/Sidebar.tsx
> +            <Filter
`<Filter ... />` would then be the actual client component, which reacts to the click event.

2023-11-07 19:47 UTC, itsjab commented on app/components/Filter.tsx
> +      onClick={handleClick}
To improve accessibility, it'd make sense to add a button here:
```tsx
<li>
  <button onClick={...}>...</button>
</li>
```

2023-11-07 19:47 UTC, itsjab commented on app/components/CatListItem.tsx
> +      {showDetails && <CatDetails catId={cat.id} onToggleOpen={toggleOpen} />}
With this implementation, you are effectively creating an overlay component for every list item, adding a lot of unnecessary elements to the DOM.

You can prevent that by "lifting state" up. Basically, you keep track of the selected cat in the `CatList` component. The overlay would live next to the grid, something like this:
```
const [selectedCat, setSelectedCat] = useState<Cat>()

return (
<>
  <CatList>
   {cats.map((cat: Cat) => (
     <CatListItem key={cat.id} cat={cat} onCatSelected={setSelectedCat} />
    ))}
</CatList>
<CatDetails cat={selectedCat} />
</>
)
```

2023-11-08 07:06 UTC, dswhy approved these changes
Not much to add to the feedback Jan already gave, specially the server component queries.

The only thing is the naming comment I left, definitely not something crucial, but important when you have several people working on the same code :D

2023-11-08 07:06 UTC, dswhy commented on app/components/CatDetails.tsx
> +export default function CatDetails({ catId, onToggleOpen }: CatDetailsProps) {
Going to be a bit nitpicky here, but the naming of functions and variables could be more explicit. For example, instead of `CatDetails` it would be clearer to name it `CatSidebar` or similar. Which then allows you to use `[catDetails, setCatDetails]` instead of just `[cat, setCat]`

2023-11-17 12:51 UTC, closed without merging